name: CD

on:
  push:
    branches: [ "publish" ]
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        default: 'test'
        type: text

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  dotnet_publish:
    name: Pack 'n' Push
    runs-on: ubuntu-latest
    
    env:
      Solution_File: ./code/F0.CodeAnalysis.Benchmarking.sln
      Packages_Directory: ./packages/

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
    - name: Pack into NuGet packages
      run: dotnet pack ${{ env.Solution_File }} --configuration Release --output ${{ env.Packages_Directory }}
    - name: Push and publish packages
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GH_PACKAGES }} --skip-duplicate
      working-directory: ${{ env.Packages_Directory }}
